import { useState } from 'react';
import { Link, NavLink, Outlet, useLocation } from 'react-router-dom';
import { Beaker, Bell, ChevronLeft, FolderKanban, LayoutDashboard, Menu, Moon, Settings, Sun } from 'lucide-react';
import type { LucideIcon } from 'lucide-react';
import { useUIStore } from '../store/ui';

const nav: { to: string; label: string; icon: LucideIcon }[] = [
  { to: '/dashboard', label: 'Overview', icon: LayoutDashboard },
  { to: '/projects', label: 'Projects', icon: FolderKanban },
  { to: '/settings', label: 'Settings', icon: Settings },
];

export function Layout() {
  const [collapsed, setCollapsed] = useState(false); const [mobileOpen, setMobileOpen] = useState(false); const { dark, toggle } = useUIStore(); const location = useLocation();
  const sidebar = <aside className={`${collapsed ? 'w-[76px]' : 'w-64'} flex shrink-0 flex-col border-r bg-white/70 p-4 backdrop-blur-xl transition-all dark:bg-slate-900/70`}>
    <div className="flex items-center justify-between px-2 py-2"><Link to="/dashboard" className="flex items-center gap-3 overflow-hidden font-bold"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-gradient-to-br from-indigo-500 to-blue-600 text-white shadow-lg shadow-indigo-200"><Beaker size={20} /></span>{!collapsed && <span className="whitespace-nowrap">Research Lab</span>}</Link><button className="btn-secondary hidden p-2 lg:inline-flex" onClick={() => setCollapsed(!collapsed)} aria-label="Collapse sidebar"><ChevronLeft size={16} className={collapsed ? 'rotate-180' : ''} /></button></div>
    <div className="my-8 px-2 text-[10px] font-bold uppercase tracking-[.2em] text-slate-400">{!collapsed && 'Workspace'}</div><nav className="space-y-1">{nav.map(({ to, label, icon: Icon }) => <NavLink onClick={() => setMobileOpen(false)} key={to} to={to} className={({ isActive }) => `flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold transition ${isActive || (to === '/projects' && location.pathname.startsWith('/projects')) ? 'bg-indigo-50 text-indigo-700 dark:bg-indigo-950/50 dark:text-indigo-300' : 'text-slate-500 hover:bg-slate-100 dark:hover:bg-slate-800'} ${collapsed ? 'justify-center' : ''}`} title={collapsed ? label : undefined}><Icon size={18} />{!collapsed && label}</NavLink>)}</nav>
    <div className="mt-auto rounded-2xl bg-gradient-to-br from-indigo-600 to-blue-600 p-4 text-white shadow-lg shadow-indigo-200 dark:shadow-indigo-950">{!collapsed ? <><p className="text-sm font-bold">Research sprint</p><p className="mt-1 text-xs text-indigo-100">Keep your evidence organized and moving.</p><Link className="mt-4 inline-flex text-xs font-bold text-white underline underline-offset-4" to="/projects">View projects →</Link></> : <Beaker size={20} className="mx-auto" />}</div>
  </aside>;
  return <div className={dark ? 'dark' : ''}><div className="flex min-h-screen"><div className={`fixed inset-y-0 left-0 z-40 flex transform transition-transform lg:static lg:translate-x-0 ${mobileOpen ? 'translate-x-0' : '-translate-x-full'}`}>{sidebar}</div>{mobileOpen && <button aria-label="Close navigation" className="fixed inset-0 z-30 bg-slate-950/40 lg:hidden" onClick={() => setMobileOpen(false)} />}<main className="min-w-0 flex-1"><header className="sticky top-0 z-20 flex h-[72px] items-center gap-4 border-b bg-white/70 px-5 backdrop-blur-xl dark:bg-slate-950/70 md:px-8"><button className="btn-secondary p-2 lg:hidden" onClick={() => setMobileOpen(true)} aria-label="Open navigation"><Menu size={18} /></button><div className="min-w-0 flex-1"><p className="truncate text-sm text-slate-400">Workspace / <span className="text-slate-600 dark:text-slate-300">{location.pathname.split('/')[1] || 'dashboard'}</span></p></div><div className="hidden max-w-xs flex-1 md:block"><input className="input" placeholder="Search your workspace..." aria-label="Search workspace" /></div><button className="btn-secondary p-2" aria-label="Notifications"><Bell size={18} /></button><button className="btn-secondary p-2" onClick={toggle} aria-label="Toggle theme">{dark ? <Sun size={18} /> : <Moon size={18} />}</button><div className="grid h-9 w-9 place-items-center rounded-full bg-gradient-to-br from-cyan-400 to-indigo-600 text-sm font-bold text-white">AR</div></header><div className="mx-auto max-w-[1500px] p-5 md:p-8"><Outlet /></div></main></div></div>;
}
