import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Edit3, FolderKanban, MoreHorizontal, Plus, Search, Trash2 } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Modal } from '../components/ui/Modal';
import { Toast, type ToastKind } from '../components/ui/Toast';
import { getApiError, projectsApi } from '../services/api';
import type { Project, ProjectPayload, ProjectStatus } from '../types';

const blank: ProjectPayload = { name: '', description: '', status: 'draft' };
const statusTone: Record<ProjectStatus, string> = { draft: 'bg-slate-100 text-slate-600', active: 'bg-emerald-50 text-emerald-700', archived: 'bg-amber-50 text-amber-700' };
function ProjectForm({ initial, pending, onCancel, onSubmit }: { initial: ProjectPayload; pending: boolean; onCancel: () => void; onSubmit: (v: ProjectPayload) => void }) {
  const [v, setV] = useState(initial); const [error, setError] = useState('');
  return <form className="space-y-4" onSubmit={(e) => { e.preventDefault(); if (!v.name.trim()) return setError('Project name is required.'); setError(''); onSubmit({ ...v, name: v.name.trim() }); }}><div><label className="label">Project name *</label><input autoFocus className="input" maxLength={160} value={v.name} onChange={e => setV({ ...v, name: e.target.value })} />{error && <p className="mt-1 text-xs text-rose-600">{error}</p>}</div><div><label className="label">Description</label><textarea className="input min-h-28" placeholder="What are you investigating?" value={v.description || ''} onChange={e => setV({ ...v, description: e.target.value })} /></div><div><label className="label">Status</label><select className="input" value={v.status} onChange={e => setV({ ...v, status: e.target.value as ProjectStatus })}><option value="draft">Draft</option><option value="active">Active</option><option value="archived">Archived</option></select></div><div className="flex justify-end gap-3 pt-2"><button type="button" className="btn-secondary" onClick={onCancel}>Cancel</button><button className="btn-primary" disabled={pending}>{pending ? 'Saving…' : 'Save project'}</button></div></form>;
}
export function Projects() {
  const qc = useQueryClient(); const [search, setSearch] = useState(''); const [editor, setEditor] = useState<'create' | 'edit' | null>(null); const [editing, setEditing] = useState<Project | null>(null); const [remove, setRemove] = useState<Project | null>(null); const [toast, setToast] = useState<{ kind: ToastKind; message: string } | null>(null);
  const query = useQuery({ queryKey: ['projects', search], queryFn: () => projectsApi.list({ search: search || undefined, page_size: 100 }).then(r => r.data.data) });
  const close = () => { setEditor(null); setEditing(null); };
  const create = useMutation({ mutationFn: projectsApi.create, onSuccess: () => { qc.invalidateQueries({ queryKey: ['projects'] }); close(); setToast({ kind: 'success', message: 'Project created.' }); }, onError: e => setToast({ kind: 'error', message: getApiError(e) }) });
  const update = useMutation({ mutationFn: ({ id, data }: { id: string; data: ProjectPayload }) => projectsApi.update(id, data), onSuccess: () => { qc.invalidateQueries({ queryKey: ['projects'] }); qc.invalidateQueries({ queryKey: ['project', editing?.id] }); close(); setToast({ kind: 'success', message: 'Project updated.' }); }, onError: e => setToast({ kind: 'error', message: getApiError(e) }) });
  const del = useMutation({ mutationFn: projectsApi.delete, onSuccess: () => { qc.invalidateQueries({ queryKey: ['projects'] }); setRemove(null); setToast({ kind: 'success', message: 'Project deleted.' }); }, onError: e => setToast({ kind: 'error', message: getApiError(e) }) });
  return <><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold text-indigo-600">Research workspace</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Projects</h1><p className="mt-2 text-slate-500">Turn big questions into organized, evidence-backed work.</p></div><button className="btn-primary" onClick={() => setEditor('create')}><Plus size={17} /> New project</button></div><div className="mb-6 flex flex-wrap items-center gap-3"><div className="relative min-w-[260px] flex-1"><Search className="absolute left-3 top-3 text-slate-400" size={17} /><input className="input pl-10" placeholder="Search projects..." value={search} onChange={e => setSearch(e.target.value)} /></div><div className="btn-secondary"><FolderKanban size={16} /> {query.data?.total ?? 0} projects</div></div>{query.isLoading ? <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{[1, 2, 3].map(i => <div className="card h-52 animate-pulse bg-slate-100 dark:bg-slate-900" key={i} />)}</div> : query.isError ? <div className="card border-rose-200 text-rose-600">Unable to load projects. Please refresh and try again.</div> : !query.data?.items.length ? <div className="card py-20 text-center"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-indigo-50 text-indigo-600"><FolderKanban /></div><h2 className="mt-5 text-lg font-bold">Nothing here yet</h2><p className="mt-2 text-slate-500">Create a project to give your research a home.</p><button className="btn-primary mt-5" onClick={() => setEditor('create')}>Create your first project</button></div> : <div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{query.data.items.map(p => <article className="card card-hover group" key={p.id}><div className="flex items-start justify-between gap-3"><span className={`rounded-full px-2.5 py-1 text-xs font-bold capitalize ${statusTone[p.status]}`}>{p.status.replace('_', ' ')}</span><button className="rounded-lg p-1 text-slate-400 opacity-0 transition hover:bg-slate-100 group-hover:opacity-100" aria-label="Project actions"><MoreHorizontal size={18} /></button></div><Link to={`/projects/${p.id}`}><h2 className="mt-5 text-lg font-bold hover:text-indigo-600">{p.name}</h2><p className="mt-2 min-h-10 line-clamp-2 text-sm leading-6 text-slate-500">{p.description || 'No description provided.'}</p></Link><div className="mt-6 flex items-center justify-between border-t pt-4 text-xs text-slate-400"><span>Updated {new Date(p.updated_at).toLocaleDateString()}</span><div className="flex gap-1"><button className="rounded-lg p-2 hover:bg-slate-100" onClick={() => { setEditing(p); setEditor('edit'); }} aria-label={`Edit ${p.name}`}><Edit3 size={15} /></button><button className="rounded-lg p-2 text-rose-500 hover:bg-rose-50" onClick={() => setRemove(p)} aria-label={`Delete ${p.name}`}><Trash2 size={15} /></button></div></div></article>)}</div>}
    <Modal open={editor === 'create'} onClose={close} title="Create project"><ProjectForm initial={blank} pending={create.isPending} onCancel={close} onSubmit={v => create.mutate(v)} /></Modal><Modal open={editor === 'edit' && Boolean(editing)} onClose={close} title="Edit project">{editing && <ProjectForm initial={{ name: editing.name, description: editing.description || '', status: editing.status }} pending={update.isPending} onCancel={close} onSubmit={data => update.mutate({ id: editing.id, data })} />}</Modal><Modal open={Boolean(remove)} onClose={() => setRemove(null)} title="Delete project"><p className="text-sm leading-6 text-slate-500">Delete <strong className="text-slate-900">{remove?.name}</strong>? This permanently removes its questions and literature.</p><div className="mt-6 flex justify-end gap-3"><button className="btn-secondary" onClick={() => setRemove(null)}>Cancel</button><button className="btn-danger" disabled={del.isPending} onClick={() => remove && del.mutate(remove.id)}><Trash2 size={16} /> {del.isPending ? 'Deleting…' : 'Delete project'}</button></div></Modal>{toast && <Toast {...toast} onClose={() => setToast(null)} />}</>;
}
